Repository nanoframework/System.Math, pull requests merged in 2021-05, with the labels that each got.

#63 Remove float overloads
  README.md
  nanoFramework.System.Math/Math.cs
  nanoFramework.System.Math/Properties/AssemblyInfo.cs
  version.json
Labels: Breaking-Change

#66 Add back Abs(float)
  nanoFramework.System.Math/Math.cs
  nanoFramework.System.Math/Properties/AssemblyInfo.cs
Labels: Type: enhancement

#67 Readd float functions
  nanoFramework.System.Math/Math.cs
  nanoFramework.System.Math/Properties/AssemblyInfo.cs
  nanoFramework.System.Math/nanoFramework.System.Math.nfproj
  nanoFramework.System.Math/packages.config
Labels: Type: bug
